---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prometheus.name }}
  labels:
    app: app-monitoring
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.prometheus.port }}
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
  selector:
    apps: {{ include "app.fullname" . }}

