apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: install-argocd-manager
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

- nonResourceURLs: [""]
  verbs: ["*"]

