apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-demo
spec:
  selector:
    matchLabels:
      app: backstage-demo
  template:
    metadata:
      labels:
        app: backstage-demo
    spec:
      containers:
     
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: backstage-demo
        
        ports:
        - name: http
          containerPort: 80