apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
     
      - image: {{ .Values.image }}
        name: guestbook-ui
        env:
          - name: CLUSTER_NAME
            value: {{ .Values.cluster }}
        ports:
        - name: http
          containerPort: 80