apiVersion: alustan.io/v1alpha1
kind: App
metadata:
  name: web-service
spec:
  environment: staging
  source:
    repoURL: https://github.com/alustan/cluster-manifests
    path: basic-demo
    releaseName: basic-demo
    targetRevision: main
    values:
      service: frontend
      image: 
        repository: alustan/web-app-demo
        tag: "1.0.1"
      database:
        connection:
          host: "{{.DB_NAME}}"
          user: "{{.DB_USER}}"
          password: "{{.DB_PASSWORD}}"
      config:
        DUMMY_1: "{{.dummy_output_1}}"
        DUMMY_2: "{{.dummy_output_2}}"

  containerRegistry:
    provider: docker
    imageName: alustan/web-app-demo
    semanticVersion: ">=0.2.0"