controller:
 extraArgs: [--aws-verify-target-group]
 metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prometheus
dashboard:
  enabled: true
 
 
