---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-aws-ebs-csi-resources
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - clusters:
        values:
          addonChart: aws-ebs-csi
        selector:
          matchLabels:
            environment: staging
            prod: false
  template:
    metadata:
      name: addon-{{name}}-{{values.addonChart}}-resources
    spec:
      project: default
      source:
        repoURL: '{{metadata.annotations.addons_git_repo}}'
        targetRevision: '{{metadata.annotations.addons_git_revision}}'
        path: 'charts/{{values.addonChart}}/resources'
        helm:
          releaseName: '{{values.addonChart}}'
          ignoreMissingValueFiles: true
          
          
      destination:
        
        name: '{{name}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true # Big CRDs.
