---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-aws-ebs-csi-resources
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - clusters:
        values:
          addonChart: aws-ebs-csi
        selector:
          matchExpressions:
         
            - key: enable_aws_ebs_csi
              operator: In
              values: ['true']
  template:
    metadata:
      name: addon-{{name}}-{{values.addonChart}}-resources
    spec:
      project: default
      source:
        repoURL: '{{metadata.annotations.addons_git_repo}}'
        targetRevision: '{{metadata.annotations.addons_git_revision}}'
        path: 'charts/{{values.addonChart}}/resources'
        helm:
          releaseName: '{{values.addonChart}}'
          ignoreMissingValueFiles: true
          valueFiles:
            - ../environments/{{metadata.labels.environment}}/{{values.addonChart}}/resources/values.yaml
          
          
      destination:
        
        name: '{{name}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true # Big CRDs.
