---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-grafana
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - merge:
        mergeKeys: [server]
        generators:
          - clusters:
              values:
                addonChart: "grafana"
               
                addonChartVersion: 7.3.0
                addonChartRepositoryNamespace: monitoring
                addonChartRepository: "https://grafana.github.io/helm-charts"
              selector:
                matchExpressions:
                
                  - key: enable_grafana
                    operator: In
                    values: ['true']
         
  template:
    metadata:
      name: addon-{{name}}-{{values.addonChart}}
    spec:
      project: default
      sources:
        - repoURL: '{{metadata.annotations.addons_git_repo}}'
          targetRevision: '{{metadata.annotations.addons_git_revision}}'
          ref: values
        - chart: '{{values.addonChart}}'
          repoURL: '{{values.addonChartRepository}}'
          targetRevision: '{{values.addonChartVersion}}'
          helm:
            releaseName: '{{values.addonChart}}'
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/environments/base/{{values.addonChart}}/values.yaml
              - $values/environments/{{metadata.labels.environment}}/{{values.addonChart}}/values.yaml

               
      destination:
        namespace: '{{values.addonChartRepositoryNamespace}}'
        name: '{{name}}'
      syncPolicy:
        automated:
          prune: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true  # Big CRDs.
