---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-ingress-nginx
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - merge:
        mergeKeys: [server]
        generators:
          - clusters:
              values:
                addonChart: ingress-nginx
                # anything not staging or prod use this version
                addonChartVersion: 4.8.1
                addonChartRepository: https://kubernetes.github.io/ingress-nginx
              
          - clusters: {}
           
  template:
    metadata:
      name: addon-{{.name}}-{{.values.addonChart}}
    spec:
      project: default
      sources:
        - repoURL: 'https://github.com/alustan/cluster-manifests/basic-ingress-controller'
          targetRevision: 'main'
          ref: values
        - chart: '{{.values.addonChart}}'
          repoURL: '{{.values.addonChartRepository}}'
          targetRevision: '{{.values.addonChartVersion}}'
          helm:
            releaseName: '{{.values.addonChart}}'
            ignoreMissingValueFiles: true
            
            values: |
              controller:
              replicaCount: 1
              service:
                
                type: LoadBalancer
               
              topologySpreadConstraints:
                - maxSkew: 1
                  topologyKey: topology.kubernetes.io/zone
                  whenUnsatisfiable: ScheduleAnyway
                  labelSelector:
                    matchLabels:
                      app.kubernetes.io/instance: ingress-nginx
                - maxSkew: 1
                  topologyKey: kubernetes.io/hostname
                  whenUnsatisfiable: ScheduleAnyway
                  labelSelector:
                    matchLabels:
                      app.kubernetes.io/instance: ingress-nginx
              minAvailable: 2
              ingressClassResource:
                name: nginx
                default: false
      destination:
        namespace: '{{.values.addonChart}}'
        name: '{{.name}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true # Big CRDs.