{{- if .Values.atlas.enabled }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}

{{- with .Values.atlas.data }}  
data:
  {{- toYaml . | nindent 2 }}
{{- end }}

{{- end }}
  