config:
 linear:
   coresPerReplica: 2
   nodesPerReplica: 1
   min: 1
   max: 100
   preventSinglePointFailure: true
   includeUnschedulableNodes: true

options:
   target: deployment/proportional-autoscaler