
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.externalNameService.dbAlias }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ExternalName
  externalName: {{ .Values.externalNameService.externalName }}