{{- if .Values.strategy.canary.enabled }}

{{- range .Values.rolloutServices }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  {{- with $.Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ $.Values.fullnameOverride }}
{{- end }}

{{- end }}
